CREATE USER ORDERO IDENTIFIED BY SYSTEM;
GRANT CREATE SESSION TO ORDERO;
GRANT CREATE TABLE TO ORDERO;
GRANT CREATE SEQUENCE TO ORDERO;
ALTER DATABASE DEFAULT TABLESPACE users;
GRANT UNLIMITED TABLESPACE TO ORDERO;


CREATE TABLE CUSTOMERS
(
CUSTOMER_ID NUMBER(6,0) NOT NULL,
FIRSTNAME VARCHAR2(50)  NOT NULL,
LASTNAME VARCHAR2(50)  NOT NULL,
STREET VARCHAR2(50) NOT NULL,
HOUSENUMBER VARCHAR(50) NOT NULL,
ZIPCODE VARCHAR(50) NOT NULL,
CITY VARCHAR2(50) NOT NULL,
COUNTRY VARCHAR2(50),
PHONE_NUMBER VARCHAR2(50) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
REGISTRATION_DATE DATE,
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)
);

CREATE SEQUENCE CUSTOMERS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE ITEMS
(
ITEM_ID NUMBER NOT NULL,
ITEM_NAME VARCHAR2(100) NOT NULL,
DESCRIPTION VARCHAR2(1000) NOT NULL,
PRICE NUMBER NOT NULL,
STOCK NUMBER NOT NULL,
BACKORDERED_ITEMS NUMBER,
CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID)
);

CREATE SEQUENCE ITEMS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE ORDERSTATUS
(
ORDERSTATUS_ID NUMBER NOT NULL,
ORDERSTATUS VARCHAR2(50) NOT NULL,
CONSTRAINT ORDERSTATUS_PK PRIMARY KEY (ORDERSTATUS_ID)
);

CREATE SEQUENCE ORDERSTATUS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE ORDERS
(
ORDER_ID NUMBER NOT NULL,
FK_CUSTOMER_ID NUMBER NOT NULL,
ORDERSTATUS VARCHAR2(50) NOT NULL,
ORDERDATE DATE NOT NULL,
CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID),
CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (FK_CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
);

CREATE SEQUENCE ORDERS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE ITEMGROUPS
(
ITEMGROUP_ID NUMBER NOT NULL,
FK_ORDER_ID NUMBER NOT NULL,
FK_ITEM_ID NUMBER NOT NULL,
ITEM_GROUP_NAME VARCHAR2(100)  NOT NULL,
DESCRIPTION VARCHAR2(1000)  NOT NULL,
PRICE NUMBER NOT NULL,
AMOUNT NUMBER NOT NULL,
SHIPPINGDATE DATE,
CONSTRAINT ITEMGROUP_PK PRIMARY KEY (ITEMGROUP_ID),
CONSTRAINT ORDER_ID_fk FOREIGN KEY (FK_ORDER_ID) REFERENCES ORDERS (ORDER_ID),
CONSTRAINT ITEM_ID_fk FOREIGN KEY (FK_ITEM_ID) REFERENCES ITEMS (ITEM_ID)
 );

CREATE SEQUENCE ITEMGROUP_SEQ
START WITH 1
INCREMENT BY 1;


DROP TABLE ITEMGROUPS;
DROP TABLE ORDERS;
DROP TABLE ITEMS;
DROP TABLE CUSTOMERS;
DROP TABLE ORDERSTATUS;